[package]
name = "backend"
version = "0.1.0"
authors = ["espectro93 <gerdes.steffen@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
